In [1]:
import pandas as pd

df=pd.read_csv("student_grades.csv")

df.head(3)

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No

In [2]:
df.iloc[2:5]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes
4,105,Rohit,Data Science,NaN,78.0,88.5,No

In [3]:
df.loc[3,"Department"]

'Electronics'

In [4]:
df.loc[3,["Name","Department"]]

Name               Anjali
Department    Electronics
Name: 3, dtype: str

In [7]:
df[df['Department']=="Computer Science"]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes

In [8]:
df[(df["Department"]=="Computer Science") & (df["Python_Score"]>95)]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes

In [11]:
df[df["Name"].isin(["Eshan","Farhan","Afsal"])]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No

In [12]:
df.sort_values(["Department","Math_Score"])

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes
7,108,Zara,Data Science,68.0,72.0,80.0,No
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes
4,105,Rohit,Data Science,NaN,78.0,88.5,No
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes
5,106,Meera,Electronics,90.0,91.0,95.0,Yes

In [13]:
df.groupby("Department")["Python_Score"].mean()

Department
Computer Science    94.666667
Data Science        79.333333
Electronics         86.000000
Name: Python_Score, dtype: float64

In [19]:
df["Passed_Numeric"]=df["Passed"].map({"Yes":1,"No":0})
df.groupby(["Department","Attendance_Pct"])["Passed_Numeric"].mean()
df.groupby("Passed_Numeric")["Attendance_Pct"].mean()

Passed_Numeric
0    84.333333
1    93.357143
Name: Attendance_Pct, dtype: float64

In [20]:
df.corr(numeric_only=True)

,Student_ID,Math_Score,Python_Score,Attendance_Pct,Passed_Numeric
Student_ID,1.000000,-0.296885,-0.181823,-0.153539,0.037987
Math_Score,-0.296885,1.000000,0.846422,0.967747,0.692530
Python_Score,-0.181823,0.846422,1.000000,0.871260,0.784982
Attendance_Pct,-0.153539,0.967747,0.871260,1.000000,0.767860
Passed_Numeric,0.037987,0.692530,0.784982,0.767860,1.000000

In [23]:
df["Total_Pct"]=((df["Math_Score"]+df["Python_Score"])/200)*100
df.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN

In [24]:
df["Passed"].value_counts()

Passed
Yes    7
No     3
Name: count, dtype: int64

Filtering in pandas

In [27]:
df[df["Passed"]=="Yes"]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
5,106,Meera,Electronics,90.0,91.0,95.0,Yes,1,90.5
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes,1,97.0
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes,1,89.5

In [28]:
df[df["Math_Score"]<80]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
7,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5

In [30]:
df[df["Python_Score"].between(70,90)]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN
7,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes,1,89.5

In [32]:
df["Department"].str.lower()

0    computer science
1        data science
2    computer science
3         electronics
4        data science
5         electronics
6    computer science
7        data science
8         electronics
9    computer science
Name: Department, dtype: str

In [34]:
df.query("Department=='Computer Science' & Python_Score>90")

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes,1,97.0

In [35]:
df.sort_values("Python_Score",na_position='first')

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
7,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes,1,89.5
5,106,Meera,Electronics,90.0,91.0,95.0,Yes,1,90.5
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes,1,97.0

In [36]:
df.nsmallest(5,"Math_Score")

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
7,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5

In [37]:
df.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN

In [38]:
df_sorted=df.sort_values("Math_Score").reset_index(drop=True)

In [39]:
df.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN

In [40]:
df_sorted.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
1,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5

In [41]:
df.groupby("Department")['Math_Score'].mean()

Department
Computer Science    87.75
Data Science        80.00
Electronics         83.00
Name: Math_Score, dtype: float64

In [42]:
df.groupby("Department")["Attendance_Pct"].agg(['mean','sum','count','max','min'])

                       mean    sum  count   max   min
Department
Computer Science  92.250000  369.0      4  98.5  84.5
Data Science      88.166667  264.5      3  96.0  80.0
Electronics       91.000000  273.0      3  95.0  87.0

In [43]:
df.drop(0)
df.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN

In [44]:
df.drop(columns=["Passed"])

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed_Numeric,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,0,NaN
5,106,Meera,Electronics,90.0,91.0,95.0,1,90.5
6,107,Aditya,Computer Science,95.0,99.0,98.5,1,97.0
7,108,Zara,Data Science,68.0,72.0,80.0,0,70.0
8,109,Kiran,Electronics,74.0,85.0,87.0,1,79.5
9,110,Siddharth,Computer Science,89.0,90.0,93.5,1,89.5

In [46]:
df.rename(columns={'Passed_Numeric':'Passed_bool'})

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed,Passed_bool,Total_Pct
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes,1,91.5
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes,1,90.0
2,103,Eshan,Computer Science,79.0,NaN,84.5,No,0,NaN
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes,1,83.5
4,105,Rohit,Data Science,NaN,78.0,88.5,No,0,NaN
5,106,Meera,Electronics,90.0,91.0,95.0,Yes,1,90.5
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes,1,97.0
7,108,Zara,Data Science,68.0,72.0,80.0,No,0,70.0
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes,1,79.5
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes,1,89.5