In [13]:
import pandas as pd

# df=pd.read_csv("student_grades.csv",usecols=["Name","Department"])
df=pd.read_csv("student_grades.csv")
df.head()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes
4,105,Rohit,Data Science,NaN,78.0,88.5,No

In [14]:
df.head(10)

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
0,101,Farhan,Computer Science,88.0,95.0,92.5,Yes
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes
4,105,Rohit,Data Science,NaN,78.0,88.5,No
5,106,Meera,Electronics,90.0,91.0,95.0,Yes
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes
7,108,Zara,Data Science,68.0,72.0,80.0,No
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes

In [15]:
df.tail()

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
5,106,Meera,Electronics,90.0,91.0,95.0,Yes
6,107,Aditya,Computer Science,95.0,99.0,98.5,Yes
7,108,Zara,Data Science,68.0,72.0,80.0,No
8,109,Kiran,Electronics,74.0,85.0,87.0,Yes
9,110,Siddharth,Computer Science,89.0,90.0,93.5,Yes

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10 non-null     int64
 1   Name            10 non-null     str
 2   Department      10 non-null     str
 3   Math_Score      9 non-null      float64
 4   Python_Score    9 non-null      float64
 5   Attendance_Pct  10 non-null     float64
 6   Passed          10 non-null     str
dtypes: float64(3), int64(1), str(3)
memory usage: 692.0 bytes

In [17]:
df.describe()

       Student_ID  Math_Score  Python_Score  Attendance_Pct
count    10.00000    9.000000      9.000000       10.000000
mean    105.50000   84.444444     86.666667       90.650000
std       3.02765    8.959787      8.426150        5.676707
min     101.00000   68.000000     72.000000       80.000000
25%     103.25000   79.000000     82.000000       87.375000
50%     105.50000   88.000000     88.000000       91.750000
75%     107.75000   90.000000     91.000000       94.625000
max     110.00000   95.000000     99.000000       98.500000

In [19]:
df.describe(include="object")

C:\Users\farhan\AppData\Local\Temp\ipykernel_26392\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

          Name        Department Passed
count       10                10     10
unique      10                 3      2
top     Farhan  Computer Science    Yes
freq         1                 4      7

In [20]:
df.isnull().sum()

Student_ID        0
Name              0
Department        0
Math_Score        1
Python_Score      1
Attendance_Pct    0
Passed            0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['Passed'].value_counts()

Passed
Yes    7
No     3
Name: count, dtype: int64

In [23]:
df['Name'].unique()

<StringArray>
[   'Farhan',     'Jasna',     'Eshan',    'Anjali',     'Rohit',     'Meera',
    'Aditya',      'Zara',     'Kiran', 'Siddharth']
Length: 10, dtype: str

In [24]:
df['Department'].nunique()

3

In [25]:
df['Department'].unique()

<StringArray>
['Computer Science', 'Data Science', 'Electronics']
Length: 3, dtype: str

In [33]:
df[['Name','Math_Score']].sort_values(by='Math_Score',ascending=False)

        Name  Math_Score
6     Aditya        95.0
1      Jasna        92.0
5      Meera        90.0
9  Siddharth        89.0
0     Farhan        88.0
3     Anjali        85.0
2      Eshan        79.0
8      Kiran        74.0
7       Zara        68.0
4      Rohit         NaN

In [34]:
df.loc[0]

Student_ID                     101
Name                        Farhan
Department        Computer Science
Math_Score                    88.0
Python_Score                  95.0
Attendance_Pct                92.5
Passed                         Yes
Name: 0, dtype: object

In [36]:
df.loc[3]

Student_ID                104
Name                   Anjali
Department        Electronics
Math_Score               85.0
Python_Score             82.0
Attendance_Pct           91.0
Passed                    Yes
Name: 3, dtype: object

In [37]:
df.loc[1:3]

,Student_ID,Name,Department,Math_Score,Python_Score,Attendance_Pct,Passed
1,102,Jasna,Data Science,92.0,88.0,96.0,Yes
2,103,Eshan,Computer Science,79.0,NaN,84.5,No
3,104,Anjali,Electronics,85.0,82.0,91.0,Yes

In [39]:
df.iloc[3]

Student_ID                104
Name                   Anjali
Department        Electronics
Math_Score               85.0
Python_Score             82.0
Attendance_Pct           91.0
Passed                    Yes
Name: 3, dtype: object